name: Build and Push Container

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Lowercase username
        run: echo "LOWER_USER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.LOWER_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set current date
        id: date
        run: echo "CACHE_DATE=$(date +'%Y-%m-%d:%H:%M:%S')" >> $GITHUB_ENV

      - name: Change working directory to repository root
        run: cd ${{ github.workspace }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.LOWER_USER }}/${{ github.event.repository.name }}:${{ github.ref_name }}
            ${{ env.REGISTRY }}/${{ env.LOWER_USER }}/${{ github.event.repository.name }}:latest
          build-args: |
            BRANCH=${{ github.ref_name }}
            USER_ID=1000
            GROUP_ID=1000
          cache-from: type=gha
          cache-to: type=gha,mode=max
